services:
  redis:
    image: redis:latest
    hostname: redis-1
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/cache:/data
      - ./data/logs/redis:/var/log/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - zy

  postgres:
    image: postgres:latest
    hostname: postgres-1
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=XXX
      - POSTGRES_USER=zy
      - POSTGRES_DB=zy
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    networks:
      - zy

networks:
  zy:
    external: true
    name: zy_default
